plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}

rootProject.name = 'devhub-b'

include 'common-module'

include 'auth-server'
include 'member-server'
include 'project-server'
include 'community-server'
include 'admin-server'
include 'media-server'
include 'notification-server'
include 'query-server'
include 'discovery-server'
include 'config-server'
include 'gateway-server'
