plugins {
    id 'org.springframework.boot'
    id 'java-library'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    runtimeOnly 'com.h2database:h2:2.3.232'
    api project(':common-module')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa:3.5.7'
    implementation 'org.springframework.boot:spring-boot-starter-security:3.5.7'
    implementation 'org.springframework.boot:spring-boot-starter-web:3.5.7'
    implementation 'org.springframework.boot:spring-boot-starter-actuator:3.5.7'
    implementation 'org.springframework.boot:spring-boot-starter-validation:3.5.7'
    implementation 'org.springframework.boot:spring-boot-starter-webflux:3.5.7'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0'
    implementation 'org.springframework.boot:spring-boot-starter-mail:3.5.7'
    implementation platform('org.springframework.cloud:spring-cloud-dependencies:2025.0.0')
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation 'org.springframework.cloud:spring-cloud-starter-loadbalancer'
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.12.2'
    testImplementation 'org.assertj:assertj-core:3.27.3'
    testImplementation 'org.mockito:mockito-core:5.15.2'
    testImplementation project(':notification-server')
    testImplementation project(':member-server')
    testCompileOnly 'org.projectlombok:lombok:1.18.38'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.38'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.12.2'
}

tasks.named('test') {
    useJUnitPlatform()
}

bootJar { archiveFileName = 'auth-server.jar' }
