spring:
  datasource:
    url: jdbc:h2:mem:media
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
server:
  port: ${MEDIA_SERVER_PORT:8086}
file:
  storage:
    root-path: ./build/devhub-media
