plugins {
    id 'org.springframework.boot'
    id 'java-library'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    runtimeOnly 'com.h2database:h2:2.3.232'
    api project(':platform')
    implementation project(':member')
    implementation project(':administration')
    implementation project(':notification')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa:3.5.7'
    implementation 'org.springframework.boot:spring-boot-starter-security:3.5.7'
    implementation 'org.springframework.boot:spring-boot-starter-web:3.5.7'
    implementation 'org.springframework.boot:spring-boot-starter-webflux:3.5.7'
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.12.2'
    testImplementation 'org.assertj:assertj-core:3.27.3'
    testImplementation 'org.mockito:mockito-core:5.15.2'
    testCompileOnly 'org.projectlombok:lombok:1.18.38'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.38'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.12.2'
}

tasks.named('test') {
    useJUnitPlatform()
}

bootJar { archiveFileName = 'identity-service.jar' }
