plugins {
    id 'org.springframework.boot'
    id 'java-library'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    runtimeOnly 'com.h2database:h2:2.3.232'
    implementation project(':platform')
    implementation project(':identity')
    implementation project(':member')
    implementation project(':project')
    implementation project(':community')
    implementation project(':administration')
    implementation project(':media')
    implementation project(':notification')
    implementation project(':readmodel')

    implementation 'org.springframework.boot:spring-boot-starter-web:3.5.7'
    implementation 'org.springframework.boot:spring-boot-starter-validation:3.5.7'
    implementation 'org.springframework.boot:spring-boot-starter-security:3.5.7'
    implementation 'org.springframework.boot:spring-boot-starter-aop:3.5.7'
    implementation 'org.springframework.data:spring-data-commons:3.5.5'
    implementation 'org.springframework:spring-tx:6.2.12'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.19.2'
    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.12.2'
    testImplementation 'org.assertj:assertj-core:3.27.3'
    testImplementation 'org.mockito:mockito-core:5.15.2'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.15.2'
    testImplementation 'org.springframework:spring-test:6.2.12'
    testImplementation 'org.hamcrest:hamcrest:3.0'
    testImplementation 'com.jayway.jsonpath:json-path:2.9.0'
    testCompileOnly 'org.projectlombok:lombok:1.18.38'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.38'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.12.2'
}

tasks.named('test') {
    useJUnitPlatform()
}

bootJar { archiveFileName = 'web-service.jar' }
